"""Pydantic models for ACT Lab system."""

from datetime import datetime

from pydantic import BaseModel, Field


class Slide(BaseModel):
    """Digital signage slide model."""

    id: int
    name: str  # Auto-generated by ACT Lab (e.g., "Slide 94")
    filename: str | None = None
    show_id: int | None = None
    start_time: datetime | None = None
    end_time: datetime | None = None
    auto_delete: bool = False
    upload_time: datetime | None = None

    model_config = {"frozen": True}


class Show(BaseModel):
    """Digital signage show model."""

    id: int
    name: str
    slides: list[Slide] = Field(default_factory=list)
    description: str | None = None

    model_config = {"frozen": True}

    @property
    def slide_count(self) -> int:
        """Get number of slides in show."""
        return len(self.slides)


class SlideUploadResult(BaseModel):
    """Result of a slide upload operation."""

    success: bool
    slide_id: int | None = None
    message: str | None = None

    model_config = {"frozen": True}
